[font]
size = 12.0

[font.normal]
family = "AnonymicePro Nerd Font Mono"
style = "Regular"

[[hints.enabled]]
command = "zen"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
opacity = 1.0
